export const departments = [
  "Computer Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biotechnology",
  "Information Technology",
  "Electronics and Communication Engineering",
  "Aerospace Engineering",
  "Automobile Engineering",
  "Architecture",
  "Fashion Design",
  "Textile Design",
  "Interior Design",
  "Graphic Design",
  "Animation and Multimedia",
  "Journalism and Mass Communication",
  "Business Administration",
  "Hotel Management",
  "Tourism Management",
  "Pharmacy",
  "Medical",
  "Dental",
  "Nursing",
  "Physiotherapy",
  "Occupational Therapy",
  "Ayurveda",
  "Homeopathy",
  "Unani",
  "Veterinary Science",
  "Agricultural Science",
  "Horticulture",
  "Forestry",
  "Environmental Science",
  "Law",
  "Fine Arts",
  "Performing Arts",
  "Visual Arts",
  "Commerce",
  "Economics",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Botany",
  "Zoology",
  "Geology",
  "Geography",
  "Anthropology",
  "Sociology",
  "Psychology",
  "Political Science",
  "History",
  "Philosophy",
  "Education",
  "Library and Information Science",
  "Physical Education",
  "Social Work",
  "Public Administration",
  "Statistics",
  "Actuarial Science",
  "Marine Engineering",
  "Mining Engineering",
  "Petroleum Engineering",
  "Naval Architecture",
  "Renewable Energy Engineering",
  "Robotics Engineering",
  "Mechatronics Engineering",
  "Biomedical Engineering",
  "Food Technology",
  "Nutrition and Dietetics",
  "Culinary Arts",
  "Event Management",
  "Anatomy",
  "Physiology",
  "Biochemistry",
  "Pathology",
  "Microbiology",
  "Pharmacology",
  "Forensic Medicine",
  "Community Medicine",
  "General Medicine",
  "Pediatrics",
  "Psychiatry",
  "Dermatology",
  "Radiology",
  "Anesthesiology",
  "Obstetrics and Gynecology",
  "Ophthalmology",
  "Orthopedics",
  "ENT (Otorhinolaryngology)",
  "Emergency Medicine",
  "Physical Medicine and Rehabilitation",
  "Sports Medicine",
  "Nuclear Medicine",
  "Pulmonary Medicine",
  "Cardiology",
  "Gastroenterology",
  "Endocrinology",
  "Nephrology",
  "Neurology",
  "Hematology",
  "Oncology",
  "Rheumatology",
  "Medical Genetics",
  "Clinical Pharmacology",
  "Geriatrics",
  "Palliative Medicine",
  "Infectious Diseases",
  "Critical Care Medicine",
  "Neonatology",
  "Interventional Radiology",
  "Vascular Surgery",
  "Neurosurgery",
  "Cardiac Surgery",
  "Pediatric Surgery",
  "Plastic Surgery",
  "Urology",
  "Transplant Surgery",
  "Surgical Oncology",
  "Medical Oncology",
  "Radiotherapy",
  "Dietetics and Nutrition",
  "Clinical Psychology",
  "Medical Education",
  "Medical Ethics",
  "Medical Informatics",
];

module.exports = departments;
