export const interests = [
  {
    category: "Programming",
    subcategories: [
      "JavaScript",
      "Python",
      "Java",
      "Flutter",
      "React Native",
      "C",
      "C#",
      "Assembly",
      "MERN Stack",
      "MEAN Stack",
      "C++",
      "OOPs",
      "DP",
      "Ruby",
      "PHP",
      "Swift",
      "TypeScript",
      "HTML/CSS",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "Solidity",
      "Ethereum",
      "Django",
      "Flask",
      "MongoDB",
      "SQL",
      "Firebase",
      "GraphQL",
      "Git",
      "Data Structures",
      "Algorithms",
      "Testing & QA",
      "Agile Methodology",
    ],
  },
  {
    category: "Movies",
    subcategories: [
      "Action",
      "Drama",
      "Comedy",
      "Sci-Fi",
      "Thriller",
      "Horror",
      "Romance",
      "Animation",
      "Fantasy",
      "Documentary",
      "Adventure",
      "Mystery",
      "Historical",
      "Musical",
      "Western",
    ],
  },
  {
    category: "Food and Cooking",
    subcategories: [
      "Culinary Arts",
      "Baking",
      "International Cuisine",
      "Healthy Eating",
      "Food Photography",
      "Homebrewing",
      "Vegetarian and Vegan Cooking",
      "Grilling and BBQ",
      "Desserts and Pastry",
      "Food Blogging",
      "Meal Planning",
      "Fermentation",
      "Spices and Seasonings",
    ],
  },
  {
    category: "Fashion",
    subcategories: [
      "Streetwear",
      "Vintage Fashion",
      "Sustainable Fashion",
      "High Fashion",
      "DIY Fashion",
      "Accessories",
      "Fashion Photography",
      "Fashion Design",
      "Fashion Illustration",
      "Fashion History",
      "Shopping and Style",
      "Makeup and Beauty",
      "Haute Couture",
      "Textile and Fabric Arts",
    ],
  },
  {
    category: "Photography",
    subcategories: [
      "Landscape Photography",
      "Portrait Photography",
      "Street Photography",
      "Wildlife Photography",
      "Macro Photography",
      "Astrophotography",
      "Fashion Photography",
      "Documentary Photography",
      "Food Photography",
      "Travel Photography",
      "Black and White Photography",
      "Underwater Photography",
      "Drone Photography",
      "Film Photography",
    ],
  },
  {
    category: "Arts",
    subcategories: [
      "Painting",
      "Sculpture",
      "Drawing",
      "Photography",
      "Digital Art",
      "Abstract Art",
      "Contemporary Art",
      "Ceramics",
      "Printmaking",
      "Installation Art",
      "Performance Art",
      "Textile Arts",
      "Street Art",
      "Glass Art",
    ],
  },
  {
    category: "Sports",
    subcategories: [
      "Football",
      "Basketball",
      "Tennis",
      "Soccer",
      "Baseball",
      "Golf",
      "Cricket",
      "Swimming",
      "Cycling",
      "Athletics",
      "Martial Arts",
      "Hockey",
      "Volleyball",
      "Rugby",
      "Cricket",
      "Snowboarding",
    ],
  },
  {
    category: "Music",
    subcategories: [
      "Rock",
      "Pop",
      "Hip Hop",
      "Electronic",
      "Jazz",
      "Classical",
      "Country",
      "Reggae",
      "Metal",
      "Blues",
      "Folk",
      "Indie",
      "R&B",
      "Soul",
      "Alternative",
      "Punk",
      "Piano",
      "Guitar",
      "Bass Guitar",
      "Drums",
      "Violin",
      "Cello",
      "Trumpet",
      "Flute",
      "Bass Guitar",
      "Harmonica",
      "Banjo",
      "Singing",
      "Songwriting",
      "Music Production",
    ],
  },
  {
    category: "Dance",
    subcategories: [
      "Ballet",
      "Bharatanatyam",
      "Kathak",
      "Odissi",
      "Kuchipudi",
      "Salsa",
      "Bihu",
      "Kathakali",
      "Manipuri",
      "Mohiniyattam",
      "Hip Hop ",
      "Ballroom Dancing",
      "Contemporary ",
      "Latin ",
      "Breakdancing",
      "Tap ",
      "Jazz ",
      "Folk Dance",
      "Bollywood Dance",
      "Irish Dance",
      "Flamenco",
      "Salsa",
      "Swing Dance",
      "K-pop Dance",
      "Belly Dance",
    ],
  },
  {
    category: "Reading",
    subcategories: [
      "Fiction",
      "Non-fiction",
      "Mystery",
      "Science Fiction",
      "Fantasy",
      "Historical Fiction",
      "Thriller",
      "Romance",
      "Horror",
      "Biography",
      "Self-Help",
      "Philosophy",
      "Business",
      "Science",
      "Travel",
    ],
  },
  {
    category: "Development",
    subcategories: [
      "Web Development",
      "App Development",
      "Game Development",
      "Database Design & Development",
      "Software Testing & QA",
      "Software Engineering",
      "Hardware Engineering",
      "Network & Security",
    ],
  },
  {
    category: "Travel",
    subcategories: [
      "Adventure",
      "Cultural",
      "Beach",
      "City Breaks",
      "Mountain Retreats",
      "Historical Sites",
      "Culinary Tourism",
      "Wildlife Safari",
      "Backpacking",
      "Cruise",
      "Solo Travel",
      "Family Vacation",
      "Road Trip",
      "Luxury Travel",
      "Ecotourism",
    ],
  },
  {
    category: "Science",
    subcategories: [
      "Physics",
      "Biology",
      "Chemistry",
      "Astronomy",
      "Geology",
      "Ecology",
      "Genetics",
      "Neuroscience",
      "Quantum Mechanics",
      "Cosmology",
      "Meteorology",
      "Paleontology",
      "Robotics",
      "Nanotechnology",
      "Biotechnology",
    ],
  },
  {
    category: "Technology",
    subcategories: [
      "Gadgets",
      "Innovation",
      "Data Science",
      "AI",
      "AWS",
      "Azure",
      "GCP",
      "Cloud Computing",
      "Blockchain",
      "Cybersecurity",
      "Augmented Reality",
      "Virtual Reality",
      "IoT (Internet of Things)",
      "Big Data",
      "Machine Learning",
      "Quantum Computing",
      "3D Printing",
      "Smart Homes",
      "Space Exploration",
      "Renewable Energy",
    ],
  },
  {
    category: "Fitness",
    subcategories: [
      "Running",
      "Yoga",
      "Weightlifting",
      "Cycling",
      "CrossFit",
      "Pilates",
      "Martial Arts",
      "Swimming",
      "Hiking",
      "Dance Fitness",
      "Mind-Body Practices",
      "Group Fitness Classes",
      "Outdoor Activities",
      "Functional Fitness",
    ],
  },
  {
    category: "Finance and Investing",
    subcategories: [
      "Personal Finance",
      "Stock Market Investing",
      "Real Estate Investment",
      "Cryptocurrency",
      "Financial Planning",
      "Frugal Living",
      "Retirement Planning",
      "Entrepreneurship",
      "Tax Planning",
      "Passive Income",
      "Economic Trends",
      "Investment Strategies",
      "Credit Management",
    ],
  },
  {
    category: "Gaming",
    subcategories: [
      "Video Games",
      "Board Games",
      "Indie Games",
      "Virtual Reality (VR) Gaming",
      "Mobile Gaming",
      "Call of Duty",
      "Among Us",
      "Minecraft",
      "Fortnite",
      "League of Legends",
      "Dota 2",
      "World of Warcraft",
      "Overwatch",
      "Apex Legends",
      "The Legend of Zelda",
      "Final Fantasy",
      "Pokemon",
      "Fall Guys",
      "Valorant",
      "PUBG",

      "Rocket League",
      "Assassin's Creed",
      "Grand Theft Auto (GTA)",
    ],
  },
];
